###### comments

# jupyter labextension install @jupyter-widgets/jupyterlab-manager @bokeh/jupyter_bokeh jupyterlab-plotly @pyviz/jupyterlab_pyviz
# jupyter lab build
# ipython kernel install --user --name=ml-htt-dev

name: ml-htt-dev
channels:
  - defaults
  - conda-forge
  - plotly
  - bokeh
dependencies:
  - python=3.8
  - pip=20.1
  - root=6.20
  - uproot=3.11
  - mplhep=0.1.21
  - scikit-learn=0.23
  - plotly=4.7
  - pandas=1.0
  - numpy=1.18
  - xgboost=1.0
  - lightgbm=2.3
  - matplotlib=3.2
  - shap=0.35
  - jupyterlab=2.1
  - hvplot=0.5
  - holoviews=1.13
  - bokeh=2.0
  - jupyter_bokeh
  - ipywidgets
  - nodejs=13.13 # required for jupyterlab extensions
prefix: /nfs/dust/cms/user/filatovo/miniconda3/envs/ml-htt-dev
  
